name: Electron Windows Release

on:
  push:
    branches:
      - main

# GitHub Actions ko force karne ke liye ke woh Node 24 use kare
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Project Dependencies
        run: npm install

      - name: Build Electron Executable (.exe)
        run: npm run build:win
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload and Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Electron App Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            release/*.exe
            release/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
